export type DebateTopic = { id: string; category: string; text: string };

const FOUNDATIONAL_TOPICS: Array<[string, string, string]> = [
  ["society", "Society", "Should social media platforms be legally liable for user content?"],
  ["society", "Society", "Is remote work better for society than office work?"],
  ["society", "Society", "Should college education be tuition-free?"],
  ["society", "Society", "Should voting be mandatory in national elections?"],
  ["society", "Society", "Should cities replace most parking spaces with green public space?"],
  ["society", "Society", "Should schools require a financial-literacy course to graduate?"],
  ["society", "Society", "Should public transit be free for all riders?"],
  ["society", "Society", "Should employers adopt four-day workweeks?"],
  ["society", "Society", "Should communities ban short-term rentals in housing shortages?"],
  ["society", "Society", "Should public libraries eliminate late fees?"],
  ["technology", "Technology", "Should governments regulate generative AI before broad deployment?"],
  ["technology", "Technology", "Should schools allow students to use AI writing assistants?"],
  ["technology", "Technology", "Should smartphones be banned during classroom instruction?"],
  ["technology", "Technology", "Should internet access be treated as a public utility?"],
  ["technology", "Technology", "Should platforms verify the identity of every social-media user?"],
  ["technology", "Technology", "Should autonomous vehicles prioritize passenger safety over pedestrian safety?"],
  ["technology", "Technology", "Should governments require repairable designs for consumer electronics?"],
  ["technology", "Technology", "Should children under sixteen need parental consent to use social media?"],
  ["technology", "Technology", "Should cashless stores be prohibited?"],
  ["technology", "Technology", "Should personal data be owned by the individual who generates it?"],
  ["ethics", "Ethics", "Is it ethical to use animals in medical research?"],
  ["ethics", "Ethics", "Should people have a right to delete their digital past?"],
  ["ethics", "Ethics", "Is it ever acceptable to lie to protect someone from harm?"],
  ["ethics", "Ethics", "Should wealthy nations accept more climate-displaced people?"],
  ["ethics", "Ethics", "Should companies be allowed to screen job applicants using AI?"],
  ["ethics", "Ethics", "Should organ donation be opt-out rather than opt-in?"],
  ["ethics", "Ethics", "Should public figures have a greater right to privacy than ordinary citizens?"],
  ["ethics", "Ethics", "Should museums return artifacts acquired during colonial rule?"],
  ["ethics", "Ethics", "Should parents publicly share images of their children online?"],
  ["ethics", "Ethics", "Should scientific experiments with high societal risks be restricted even if they promise benefits?"],
  ["environment", "Environment", "Should governments ban new gasoline-powered car sales by 2035?"],
  ["environment", "Environment", "Should nuclear power be central to climate strategy?"],
  ["environment", "Environment", "Should air travel include a meaningful carbon tax?"],
  ["environment", "Environment", "Should cities ban single-use plastic packaging?"],
  ["environment", "Environment", "Should climate activism include disruptive protests?"],
  ["environment", "Environment", "Should water-intensive lawns be restricted in drought-prone areas?"],
  ["environment", "Environment", "Should developing countries be allowed to prioritize economic growth over emissions cuts?"],
  ["environment", "Environment", "Should meat consumption be taxed for environmental reasons?"],
  ["environment", "Environment", "Should governments subsidize home solar panels?"],
  ["environment", "Environment", "Should national parks limit visitor access to protect ecosystems?"],
  ["education", "Education", "Should schools replace letter grades with mastery-based assessment?"],
  ["education", "Education", "Should homework be abolished in elementary school?"],
  ["education", "Education", "Should universities require students to take humanities courses?"],
  ["education", "Education", "Should school uniforms be mandatory?"],
  ["education", "Education", "Should student athletes be paid for representing their schools?"],
  ["education", "Education", "Should standardized tests play a major role in university admissions?"],
  ["education", "Education", "Should coding be a required subject in secondary school?"],
  ["education", "Education", "Should classes start later for teenagers?"],
  ["education", "Education", "Should schools teach debate as a core subject?"],
  ["education", "Education", "Should public funding cover trade schools as fully as universities?"],
  ["economy", "Economy", "Should governments introduce a universal basic income?"],
  ["economy", "Economy", "Should the minimum wage be indexed automatically to inflation?"],
  ["economy", "Economy", "Should large corporations pay a higher tax rate than small businesses?"],
  ["economy", "Economy", "Should governments cap rent increases in expensive cities?"],
  ["economy", "Economy", "Should unpaid internships be illegal?"],
  ["economy", "Economy", "Should gig-economy workers receive full employee protections?"],
  ["economy", "Economy", "Should public companies disclose CEO-to-worker pay ratios?"],
  ["economy", "Economy", "Should countries prioritize local manufacturing over lower consumer prices?"],
  ["economy", "Economy", "Should inheritances be taxed more heavily?"],
  ["economy", "Economy", "Should housing be considered an investment or a human right?"],
  ["health", "Health", "Should governments tax sugary drinks?"],
  ["health", "Health", "Should mental-health days be treated like sick days at work?"],
  ["health", "Health", "Should governments require childhood vaccinations for public-school attendance?"],
  ["health", "Health", "Should healthcare systems prioritize prevention over treatment?"],
  ["health", "Health", "Should contact sports be restricted for children?"],
  ["health", "Health", "Should employers be allowed to offer wellness incentives tied to health data?"],
  ["health", "Health", "Should governments regulate ultra-processed food advertising to children?"],
  ["health", "Health", "Should assisted dying be legal for terminally ill adults?"],
  ["health", "Health", "Should pharmacies provide more primary-care services?"],
  ["health", "Health", "Should schools provide free menstrual products?"],
  ["culture", "Culture", "Should fictional works be judged by the creator's personal conduct?"],
  ["culture", "Culture", "Should professional sports leagues use salary caps?"],
  ["culture", "Culture", "Should streaming services release entire seasons at once?"],
  ["culture", "Culture", "Should cities fund public art before other cultural programs?"],
  ["culture", "Culture", "Should national teams select athletes based only on merit, not representation?"],
  ["culture", "Culture", "Should books with offensive language remain in school libraries?"],
  ["culture", "Culture", "Should heritage sites charge tourists more than local residents?"],
  ["culture", "Culture", "Should influencers disclose digitally altered images?"],
  ["culture", "Culture", "Should public broadcasters be funded by taxes?"],
  ["culture", "Culture", "Should celebrities be held to higher standards of public conduct?"],
  ["future", "Future", "Should humans prioritize settling Mars over fixing Earth’s problems?"],
  ["future", "Future", "Should cities prepare for a future without privately owned cars?"],
  ["future", "Future", "Should human genetic enhancement be legal for adults?"],
  ["future", "Future", "Should governments guarantee jobs displaced by automation?"],
  ["future", "Future", "Should digital identities replace physical IDs?"],
  ["future", "Future", "Should democratic governments give future generations formal representation?"],
  ["future", "Future", "Should AI-generated art be eligible for major awards?"],
  ["future", "Future", "Should space resources belong to all humanity?"],
  ["future", "Future", "Should nations create a global tax on automated labor?"],
  ["future", "Future", "Should people be able to sell access to their personal genetic data?"],
  ["playful", "Playful", "Is a hot dog a sandwich?"],
  ["playful", "Playful", "Should pineapple be accepted as a pizza topping?"],
  ["playful", "Playful", "Is it better to be an early bird than a night owl?"],
  ["playful", "Playful", "Should people reread favorite books instead of always seeking new ones?"],
  ["playful", "Playful", "Is a window seat better than an aisle seat?"],
  ["playful", "Playful", "Should board games replace video games for family nights?"],
  ["playful", "Playful", "Is breakfast truly the most important meal of the day?"],
  ["playful", "Playful", "Should dessert be eaten before dinner?"],
  ["playful", "Playful", "Is it better to explore a new city alone or with friends?"],
  ["playful", "Playful", "Should every workplace allow pets?"],
];

const EXPANDED_TOPICS: Array<[string, string, string]> = [
  ["law-rights", "Law & Rights", "Should jury service be paid at a professional wage?"],
  ["law-rights", "Law & Rights", "Should governments ban non-compete clauses for most workers?"],
  ["law-rights", "Law & Rights", "Should voting districts be drawn by independent commissions?"],
  ["law-rights", "Law & Rights", "Should the voting age be lowered to sixteen?"],
  ["law-rights", "Law & Rights", "Should courts allow cameras in all public trials?"],
  ["law-rights", "Law & Rights", "Should governments require platforms to explain algorithmic decisions?"],
  ["law-rights", "Law & Rights", "Should public schools permit students to protest during school hours?"],
  ["law-rights", "Law & Rights", "Should copyright terms be substantially shorter?"],
  ["law-rights", "Law & Rights", "Should governments make election day a public holiday?"],
  ["law-rights", "Law & Rights", "Should civil disobedience receive lighter penalties when it is nonviolent?"],
  ["global", "Global Affairs", "Should countries prioritize regional alliances over global institutions?"],
  ["global", "Global Affairs", "Should foreign aid be tied to measurable governance reforms?"],
  ["global", "Global Affairs", "Should countries open their labor markets more widely to migrants?"],
  ["global", "Global Affairs", "Should wealthier nations forgive more sovereign debt owed by poorer nations?"],
  ["global", "Global Affairs", "Should international sporting events be boycotted over human-rights concerns?"],
  ["global", "Global Affairs", "Should countries spend more on diplomacy than on military expansion?"],
  ["global", "Global Affairs", "Should global internet governance be controlled by national governments?"],
  ["global", "Global Affairs", "Should countries share climate technology without patent restrictions?"],
  ["global", "Global Affairs", "Should asylum claims be processed by international rather than national bodies?"],
  ["global", "Global Affairs", "Should nations limit foreign ownership of critical infrastructure?"],
  ["science", "Science", "Should governments fund basic science even when applications are uncertain?"],
  ["science", "Science", "Should peer review be open by default?"],
  ["science", "Science", "Should research using public funds be freely accessible to everyone?"],
  ["science", "Science", "Should scientists communicate uncertainty more prominently in public debates?"],
  ["science", "Science", "Should private companies be allowed to own genetic discoveries?"],
  ["science", "Science", "Should laboratories publish negative results more often?"],
  ["science", "Science", "Should governments prioritize space science over deep-ocean research?"],
  ["science", "Science", "Should citizens have a direct vote on high-risk scientific projects?"],
  ["science", "Science", "Should public agencies restrict research on technologies with clear misuse potential?"],
  ["science", "Science", "Should scientific expertise receive more weight than public opinion in technical policy?"],
  ["work", "Work & Leadership", "Should employers publish salary ranges for every role?"],
  ["work", "Work & Leadership", "Should managers be elected by their teams?"],
  ["work", "Work & Leadership", "Should all workers have a legal right to disconnect after hours?"],
  ["work", "Work & Leadership", "Should companies hire for potential over prior experience?"],
  ["work", "Work & Leadership", "Should employers offer paid sabbaticals after long service?"],
  ["work", "Work & Leadership", "Should promotions require evidence of mentoring others?"],
  ["work", "Work & Leadership", "Should job applications exclude university names to reduce bias?"],
  ["work", "Work & Leadership", "Should most offices make remote work the default?"],
  ["work", "Work & Leadership", "Should companies measure performance by outcomes rather than hours online?"],
  ["work", "Work & Leadership", "Should every worker receive ownership shares in profitable companies?"],
  ["philosophy", "Philosophy", "Is a meaningful life more important than a happy life?"],
  ["philosophy", "Philosophy", "Should people prioritize loyalty over impartial fairness?"],
  ["philosophy", "Philosophy", "Is personal identity preserved if every memory is copied digitally?"],
  ["philosophy", "Philosophy", "Should intentions matter more than consequences when judging actions?"],
  ["philosophy", "Philosophy", "Is it better to seek truth than social harmony?"],
  ["philosophy", "Philosophy", "Should people have a moral duty to be optimistic about the future?"],
  ["philosophy", "Philosophy", "Can an action be admirable if it is motivated by self-interest?"],
  ["philosophy", "Philosophy", "Should people forgive others without an apology?"],
  ["philosophy", "Philosophy", "Is equality more important than freedom?"],
  ["philosophy", "Philosophy", "Should humanity preserve traditions even when they slow progress?"],
  ["media", "Media & Information", "Should news outlets avoid reporting on unverified viral claims?"],
  ["media", "Media & Information", "Should social platforms label all AI-generated political media?"],
  ["media", "Media & Information", "Should journalists reveal anonymous sources only in exceptional cases?"],
  ["media", "Media & Information", "Should public figures have a right to reply in articles about them?"],
  ["media", "Media & Information", "Should search engines rank authoritative sources above popular ones?"],
  ["media", "Media & Information", "Should news organizations separate commentary from reporting more clearly?"],
  ["media", "Media & Information", "Should platforms pay publishers when news links are shared?"],
  ["media", "Media & Information", "Should school curricula include media-literacy exams?"],
  ["media", "Media & Information", "Should livestream platforms delay broadcasts to improve safety moderation?"],
  ["media", "Media & Information", "Should online pseudonyms receive the same protections as real names?"],
  ["cities", "Cities & Transport", "Should city centers charge private vehicles a congestion fee?"],
  ["cities", "Cities & Transport", "Should suburbs permit more multi-family housing by default?"],
  ["cities", "Cities & Transport", "Should cities convert one traffic lane on major roads into protected bike lanes?"],
  ["cities", "Cities & Transport", "Should historic preservation rules yield to housing construction?"],
  ["cities", "Cities & Transport", "Should cities offer free late-night public transport?"],
  ["cities", "Cities & Transport", "Should local governments ban drive-through restaurants in dense neighborhoods?"],
  ["cities", "Cities & Transport", "Should cities require new buildings to include affordable housing?"],
  ["cities", "Cities & Transport", "Should ride-hailing companies be regulated like taxis?"],
  ["cities", "Cities & Transport", "Should all new streets prioritize pedestrians before vehicle throughput?"],
  ["cities", "Cities & Transport", "Should urban delivery vehicles be limited to off-peak hours?"],
  ["sport", "Sport & Games", "Should elite athletes be allowed to use performance-enhancing technology?"],
  ["sport", "Sport & Games", "Should youth sports place equal playing time above winning?"],
  ["sport", "Sport & Games", "Should professional leagues use video review less often?"],
  ["sport", "Sport & Games", "Should esports be included in major multi-sport competitions?"],
  ["sport", "Sport & Games", "Should college athletes be allowed to transfer freely between schools?"],
  ["sport", "Sport & Games", "Should sports teams be publicly owned by their communities?"],
  ["sport", "Sport & Games", "Should high-risk sports require more stringent safety rules?"],
  ["sport", "Sport & Games", "Should chess be considered a sport?"],
  ["sport", "Sport & Games", "Should games prioritize accessibility options even when they change difficulty?"],
  ["sport", "Sport & Games", "Should competitive games reward teamwork more than individual statistics?"],
  ["lifestyle", "Lifestyle", "Should people rent more possessions instead of owning them?"],
  ["lifestyle", "Lifestyle", "Should restaurants eliminate tipping in favor of higher listed prices?"],
  ["lifestyle", "Lifestyle", "Should people take a digital-free day every week?"],
  ["lifestyle", "Lifestyle", "Should cities regulate the number of chain restaurants in a neighborhood?"],
  ["lifestyle", "Lifestyle", "Is it better to buy fewer expensive items than many inexpensive items?"],
  ["lifestyle", "Lifestyle", "Should grocery stores disclose the environmental impact of food?"],
  ["lifestyle", "Lifestyle", "Should adults learn a second language as a civic expectation?"],
  ["lifestyle", "Lifestyle", "Should public spaces provide more quiet zones?"],
  ["lifestyle", "Lifestyle", "Should people prioritize local food over year-round variety?"],
  ["lifestyle", "Lifestyle", "Should cities restrict late-night food delivery services?"],
  ["arts", "Arts & Design", "Should public art be selected by citizen vote?"],
  ["arts", "Arts & Design", "Should architecture prioritize beauty over efficiency?"],
  ["arts", "Arts & Design", "Should museums charge admission to support ambitious programming?"],
  ["arts", "Arts & Design", "Should artists be allowed to train AI models on publicly visible work?"],
  ["arts", "Arts & Design", "Should cities protect independent music venues from redevelopment?"],
  ["arts", "Arts & Design", "Should design schools prioritize hand skills over digital tools?"],
  ["arts", "Arts & Design", "Should public monuments be reinterpreted rather than removed?"],
  ["arts", "Arts & Design", "Should art competitions allow anonymous entries?"],
  ["arts", "Arts & Design", "Should fashion brands be held responsible for textile waste?"],
  ["arts", "Arts & Design", "Should public buildings commission local artists for new projects?"],
];

export const TOPICS: DebateTopic[] = [...FOUNDATIONAL_TOPICS, ...EXPANDED_TOPICS]
  .map(([id, category, text], index) => ({ id: `${id}-${index}`, category, text }));

export const TOPIC_CATEGORIES = ["Random", "All", ...Array.from(new Set(TOPICS.map(topic => topic.category)))];

export function chooseTopic(category: string, avoidIds: string[] = [], random = Math.random) {
  const pool = TOPICS.filter(topic => category === "All" || category === "Random" || topic.category === category);
  const freshPool = pool.filter(topic => !avoidIds.includes(topic.id));
  const selectionPool = freshPool.length ? freshPool : pool;
  return selectionPool[Math.floor(random() * selectionPool.length)] ?? TOPICS[0];
}

export function appendRecentTopic(recentIds: string[], topicId: string, limit = 8) {
  return [...recentIds.filter(id => id !== topicId), topicId].slice(-limit);
}
