export type DebateTopic = { id: string; category: string; text: string };

export const TOPICS: DebateTopic[] = [
  ["society", "Society", "Should social media platforms be legally liable for user content?"],
  ["society", "Society", "Is remote work better for society than office work?"],
  ["society", "Society", "Should college education be tuition-free?"],
  ["society", "Society", "Should voting be mandatory in national elections?"],
  ["society", "Society", "Should cities replace most parking spaces with green public space?"],
  ["society", "Society", "Should schools require a financial-literacy course to graduate?"],
  ["society", "Society", "Should public transit be free for all riders?"],
  ["society", "Society", "Should employers adopt four-day workweeks?"],
  ["society", "Society", "Should communities ban short-term rentals in housing shortages?"],
  ["society", "Society", "Should public libraries eliminate late fees?"],
  ["technology", "Technology", "Should governments regulate generative AI before broad deployment?"],
  ["technology", "Technology", "Should schools allow students to use AI writing assistants?"],
  ["technology", "Technology", "Should smartphones be banned during classroom instruction?"],
  ["technology", "Technology", "Should internet access be treated as a public utility?"],
  ["technology", "Technology", "Should platforms verify the identity of every social-media user?"],
  ["technology", "Technology", "Should autonomous vehicles prioritize passenger safety over pedestrian safety?"],
  ["technology", "Technology", "Should governments require repairable designs for consumer electronics?"],
  ["technology", "Technology", "Should children under sixteen need parental consent to use social media?"],
  ["technology", "Technology", "Should cashless stores be prohibited?"],
  ["technology", "Technology", "Should personal data be owned by the individual who generates it?"],
  ["ethics", "Ethics", "Is it ethical to use animals in medical research?"],
  ["ethics", "Ethics", "Should people have a right to delete their digital past?"],
  ["ethics", "Ethics", "Is it ever acceptable to lie to protect someone from harm?"],
  ["ethics", "Ethics", "Should wealthy nations accept more climate-displaced people?"],
  ["ethics", "Ethics", "Should companies be allowed to screen job applicants using AI?"],
  ["ethics", "Ethics", "Should organ donation be opt-out rather than opt-in?"],
  ["ethics", "Ethics", "Should public figures have a greater right to privacy than ordinary citizens?"],
  ["ethics", "Ethics", "Should museums return artifacts acquired during colonial rule?"],
  ["ethics", "Ethics", "Should parents publicly share images of their children online?"],
  ["ethics", "Ethics", "Should scientific experiments with high societal risks be restricted even if they promise benefits?"],
  ["environment", "Environment", "Should governments ban new gasoline-powered car sales by 2035?"],
  ["environment", "Environment", "Should nuclear power be central to climate strategy?"],
  ["environment", "Environment", "Should air travel include a meaningful carbon tax?"],
  ["environment", "Environment", "Should cities ban single-use plastic packaging?"],
  ["environment", "Environment", "Should climate activism include disruptive protests?"],
  ["environment", "Environment", "Should water-intensive lawns be restricted in drought-prone areas?"],
  ["environment", "Environment", "Should developing countries be allowed to prioritize economic growth over emissions cuts?"],
  ["environment", "Environment", "Should meat consumption be taxed for environmental reasons?"],
  ["environment", "Environment", "Should governments subsidize home solar panels?"],
  ["environment", "Environment", "Should national parks limit visitor access to protect ecosystems?"],
  ["education", "Education", "Should schools replace letter grades with mastery-based assessment?"],
  ["education", "Education", "Should homework be abolished in elementary school?"],
  ["education", "Education", "Should universities require students to take humanities courses?"],
  ["education", "Education", "Should school uniforms be mandatory?"],
  ["education", "Education", "Should student athletes be paid for representing their schools?"],
  ["education", "Education", "Should standardized tests play a major role in university admissions?"],
  ["education", "Education", "Should coding be a required subject in secondary school?"],
  ["education", "Education", "Should classes start later for teenagers?"],
  ["education", "Education", "Should schools teach debate as a core subject?"],
  ["education", "Education", "Should public funding cover trade schools as fully as universities?"],
  ["economy", "Economy", "Should governments introduce a universal basic income?"],
  ["economy", "Economy", "Should the minimum wage be indexed automatically to inflation?"],
  ["economy", "Economy", "Should large corporations pay a higher tax rate than small businesses?"],
  ["economy", "Economy", "Should governments cap rent increases in expensive cities?"],
  ["economy", "Economy", "Should unpaid internships be illegal?"],
  ["economy", "Economy", "Should gig-economy workers receive full employee protections?"],
  ["economy", "Economy", "Should public companies disclose CEO-to-worker pay ratios?"],
  ["economy", "Economy", "Should countries prioritize local manufacturing over lower consumer prices?"],
  ["economy", "Economy", "Should inheritances be taxed more heavily?"],
  ["economy", "Economy", "Should housing be considered an investment or a human right?"],
  ["health", "Health", "Should governments tax sugary drinks?"],
  ["health", "Health", "Should mental-health days be treated like sick days at work?"],
  ["health", "Health", "Should governments require childhood vaccinations for public-school attendance?"],
  ["health", "Health", "Should healthcare systems prioritize prevention over treatment?"],
  ["health", "Health", "Should contact sports be restricted for children?"],
  ["health", "Health", "Should employers be allowed to offer wellness incentives tied to health data?"],
  ["health", "Health", "Should governments regulate ultra-processed food advertising to children?"],
  ["health", "Health", "Should assisted dying be legal for terminally ill adults?"],
  ["health", "Health", "Should pharmacies provide more primary-care services?"],
  ["health", "Health", "Should schools provide free menstrual products?"],
  ["culture", "Culture", "Should fictional works be judged by the creator's personal conduct?"],
  ["culture", "Culture", "Should professional sports leagues use salary caps?"],
  ["culture", "Culture", "Should streaming services release entire seasons at once?"],
  ["culture", "Culture", "Should cities fund public art before other cultural programs?"],
  ["culture", "Culture", "Should national teams select athletes based only on merit, not representation?"],
  ["culture", "Culture", "Should books with offensive language remain in school libraries?"],
  ["culture", "Culture", "Should heritage sites charge tourists more than local residents?"],
  ["culture", "Culture", "Should influencers disclose digitally altered images?"],
  ["culture", "Culture", "Should public broadcasters be funded by taxes?"],
  ["culture", "Culture", "Should celebrities be held to higher standards of public conduct?"],
  ["future", "Future", "Should humans prioritize settling Mars over fixing Earth’s problems?"],
  ["future", "Future", "Should cities prepare for a future without privately owned cars?"],
  ["future", "Future", "Should human genetic enhancement be legal for adults?"],
  ["future", "Future", "Should governments guarantee jobs displaced by automation?"],
  ["future", "Future", "Should digital identities replace physical IDs?"],
  ["future", "Future", "Should democratic governments give future generations formal representation?"],
  ["future", "Future", "Should AI-generated art be eligible for major awards?"],
  ["future", "Future", "Should space resources belong to all humanity?"],
  ["future", "Future", "Should nations create a global tax on automated labor?"],
  ["future", "Future", "Should people be able to sell access to their personal genetic data?"],
  ["playful", "Playful", "Is a hot dog a sandwich?"],
  ["playful", "Playful", "Should pineapple be accepted as a pizza topping?"],
  ["playful", "Playful", "Is it better to be an early bird than a night owl?"],
  ["playful", "Playful", "Should people reread favorite books instead of always seeking new ones?"],
  ["playful", "Playful", "Is a window seat better than an aisle seat?"],
  ["playful", "Playful", "Should board games replace video games for family nights?"],
  ["playful", "Playful", "Is breakfast truly the most important meal of the day?"],
  ["playful", "Playful", "Should dessert be eaten before dinner?"],
  ["playful", "Playful", "Is it better to explore a new city alone or with friends?"],
  ["playful", "Playful", "Should every workplace allow pets?"],
].map(([id, category, text], index) => ({ id: `${id}-${index}`, category, text }));

export const TOPIC_CATEGORIES = ["All", ...Array.from(new Set(TOPICS.map(topic => topic.category)))];
